PLMVC/Models/CustomerView.cs
namespace PLMVC.Models
{
    public class CustomerView
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
    }
}

PLMVC/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Interfaces;
using PLMVC.Infrastructure;
using AutoMapper;
using BLL.ObjectsDTO;
using PLMVC.Models;

namespace PLMVC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService customerService;
        public CustomerController()
        {
            customerService = Conf.GetService(typeof(ICustomerService)) as ICustomerService;
        }

        public ActionResult GetAll()
        {
            var customers = customerService.GetAllCustomers();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CustomerDTO, CustomerView>()).CreateMapper();
            var customersView = mapper.Map<IEnumerable<CustomerDTO>, IEnumerable<CustomerView>>(customers);
            ViewBag.Customers = customersView;
            return View("ListOfCustomers");
        }

        public ActionResult FindCustomerByEmail()
        {
            return View("FindCustomerByEmail");
        }

        [HttpPost]
        public ActionResult FindCustomerByEmail(CustomerView customerViewInput)
        {
            try
            {
                var customer = customerService.GetUserByEmail(customerViewInput.CustomerEmail);
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CustomerDTO, CustomerView>()).CreateMapper();
                var customerView = mapper.Map<CustomerDTO, CustomerView>(customer);
                ViewBag.Customers = new List<CustomerView>() { customerView };
                return View("ListOfCustomers");
            }
            catch (Exception e)
            {
                ViewData["ExceptionMessage"] = e.Message;
                return View("ExceptionMessage");
            }
        }

        public ActionResult AddCustomerFields()
        {
            return View();
        }


        [HttpPost]
        public IActionResult AddCustomerFields(CustomerView customerView)
        {
            try
            {
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CustomerView, CustomerDTO>()).CreateMapper();
                var customersDTO = mapper.Map<CustomerView, CustomerDTO>(customerView);
                customerService.AddCustomerToDB(customersDTO);
                return RedirectToAction("GetAll");
            }
            catch (Exception e)
            {
                ViewData["ExceptionMessage"] = e.Message;
                return View("ExceptionMessage");
            }
        }

        public ActionResult EditCustomerFields()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EditCustomerFields(int id, CustomerView customerView)
        {
            try
            {
                customerView.CustomerId = id;
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CustomerView, CustomerDTO>()).CreateMapper();
                var customersDTO = mapper.Map<CustomerView, CustomerDTO>(customerView);
                customerService.UpdateCustomer(customersDTO);
                return RedirectToAction("GetAll");
            }
            catch (Exception e)
            {
                ViewData["ExceptionMessage"] = e.Message;
                return View("ExceptionMessage");
            }
        }

        public ActionResult DeleteCustomer(int id)
        {
            try
            {
                var customersDTO = customerService.GetUserById(id);
                customerService.DeleteCustomer(customersDTO);
                return RedirectToAction("GetAll");
            }
            catch (Exception e)
            {
                ViewData["ExceptionMessage"] = e.Message;
                return View("ExceptionMessage");
            }
        }
    }
}

PLMVC/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BLL.ObjectsDTO;
using PLMVC.Models;
using BLL.Interfaces;
using PLMVC.Infrastructure;

namespace PLMVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;
        private readonly IProductService productService;
        public OrderController()
        {
            orderService = Conf.GetService(typeof(IOrderService)) as IOrderService;
            productService = Conf.GetService(typeof(IProductService)) as IProductService;
        }
        public ActionResult GetCustomerOrders(int id)
        {
            try
            {
                ViewBag.OrderCustomerId = id;

                var orders = orderService.GetOrdersByCustomerId(id);
                var mapper = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<OrderDTO, OrderView>();
                    cfg.CreateMap<ProductDTO, ProductView>();
                }).CreateMapper();
                var orderViews = mapper.Map<IEnumerable<OrderDTO>, IEnumerable<OrderView>>(orders);
                var orderProducts = new Dictionary<int, IEnumerable<ProductView>>();
                foreach (var order in orderViews)
                {
                    var products = orderService.GetProductsByOrderId(order.OrderId);
                    orderProducts.Add(order.OrderId,
                        mapper.Map<IEnumerable<ProductDTO>, IEnumerable<ProductView>>(products));
                }
                ViewBag.CustomerOrders = orderProducts;

                return View();
            }
            catch (Exception e)
            {
                ViewData["ExceptionMessage"] = e.Message;
                if (e.Message == "Customer hasn't any order")
                {
                    return View("NullOrdersException");
                }

                return View("ExceptionMessage");
            }
        }
        public ActionResult DeleteProductFromOrder(int customerId, int orderId, int productId)
        {
            try
            {
                orderService.RemoveProductFromOrder(productId, orderId);
                return RedirectToAction("GetCustomerOrders", new { id = customerId });
            }
            catch (Exception e)
            {
                ViewData["ExceptionMessage"] = e.Message;
                return View("ExceptionMessage");
            }
        }

        public ActionResult AddProductToOrder(int customerId, int orderId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddProductToOrder(int customerId, int orderId, ProductView productView)
        {
            try
            {
                orderService.AddProductToOrder(productService.GetProductByName(productView.ProductName).ProductId, orderId);
                return RedirectToAction("GetCustomerOrders", new { id = customerId });
            }
            catch (Exception e)
            {
                ViewData["ExceptionMessage"] = e.Message;
                return View("ExceptionMessage");
            }
        }

        public ActionResult DeleteOrder(int customerId, int orderId)
        {
            try
            {
                orderService.DeleteOrderById(orderId);
                return RedirectToAction("GetCustomerOrders", new { id = customerId });
            }
            catch (Exception e)
            {
                ViewData["ExceptionMessage"] = e.Message;
                return View("ExceptionMessage");
            }
        }


        public ActionResult CreateOrder(int customerId)
        {
            try
            {
                orderService.CreateOrder(new OrderDTO() { CustomerId = customerId });
                return RedirectToAction("GetCustomerOrders", new { id = customerId });
            }
            catch (Exception e)
            {
                ViewData["ExceptionMessage"] = e.Message;
                return View("ExceptionMessage");
            }
        }

    }
}

PLMVC/Views/Customer/AddCustomerFields.cshtml
@using PLMVC.Controllers
@{
    ViewData["Title"] = "AddCustomer";
}
<h1>@ViewData["Title"]</h1>

<table>
    <form method="post" action="">
        <p>
            <label>Name:</label><br />
            <input type="text" name="CustomerName" />
        </p>
        <p>
            <label>Email:</label><br />
            <input type="Email" name="CustomerEmail" />
        </p>
        <p>
            <input type="submit" value="Отправить" />
        </p>
    </form>
</table>

PLMVC/Views/Customer/EditCustomerFields.cshtml
@using PLMVC.Controllers
@{
    ViewData["Title"] = "EditCustomer";
}
<h1>@ViewData["Title"]</h1>

<table>
    <form method="post" action="">
        <p>
            <label>Name:</label><br />
            <input type="text" name="CustomerName"/>
        </p>
        <p>
            <label>Email:</label><br />
            <input type="Email" name="CustomerEmail" />
        </p>
        <p>
            <input type="submit" value="Отправить" />
        </p>
    </form>
</table>

PLMVC/Views/Customer/FindCustomerByEmail.cshtml
@using PLMVC.Controllers
@{
    ViewData["Title"] = "Find Customer";
}
<h1>@ViewData["Title"]</h1>

<table>
    <form method="post" action="">
        <p>
            <label>Email:</label><br />
            <input type="Email" name="CustomerEmail" />
        </p>
        <p>
            <input type="submit" value="Отправить" />
        </p>
    </form>
</table>

PLMVC/Views/Customer/ListOfCustomers.cshtml
@using PLMVC.Controllers
@{
    ViewData["Customer"] = "Customer";
}
<h1>@ViewData["Customer"]</h1>

<table>
    <tr>
        <td>Id</td>
        <td>|</td>
        <td>Name</td>
        <td>|</td>
        <td>Email</td>
    </tr>
    @foreach (var customer in ViewBag.Customers)
    {
<tr>
    <td>@customer.CustomerId</td>
    <td>|</td>
    <td>@customer.CustomerName</td>
    <td>|</td>
    <td>@customer.CustomerEmail</td>
    <td>|</td>
    <td><a asp-action="GetCustomerOrders" asp-controller="Order" asp-route-id="@customer.CustomerId">Orders</a></td>
    <td>|</td>
    <td><a asp-action="DeleteCustomer" asp-route-id="@customer.CustomerId">Delete</a></td>
    <td>|</td>
    <td><a asp-action="EditCustomerFields" asp-route-id="@customer.CustomerId">Edit</a></td>
</tr>
}
</table>